No display found. Using non-interactive Agg backend
Switched to: Agg
Traceback (most recent call last):
  File "/Users/anniezhou/Desktop/NeuralLCB_C/realworld_main.py", line 68, in <module>
    from xgboost import XGBRegressor
  File "/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/__init__.py", line 6, in <module>
    from . import tracker  # noqa
  File "/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/tracker.py", line 9, in <module>
    from .core import _LIB, _check_call, make_jcargs
  File "/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/core.py", line 269, in <module>
    _LIB = _load_lib()
  File "/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/core.py", line 222, in _load_lib
    raise XGBoostError(
xgboost.core.XGBoostError: 
XGBoost Library (libxgboost.dylib) could not be loaded.
Likely causes:
  * OpenMP runtime is not installed
    - vcomp140.dll or libgomp-1.dll for Windows
    - libomp.dylib for Mac OSX
    - libgomp.so for Linux and other UNIX-like OSes
    Mac OSX users: Run `brew install libomp` to install OpenMP runtime.

  * You are running 32-bit Python on a 64-bit OS

Error message(s): ["dlopen(/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/lib/libxgboost.dylib, 0x0006): Library not loaded: @rpath/libomp.dylib\n  Referenced from: <B22D7F05-77FA-34A6-8757-C605D2CFE1AD> /opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/lib/libxgboost.dylib\n  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/lib-dynload/../../libomp.dylib' (no such file), '/opt/anaconda3/envs/jaxcpu_tf28/bin/../lib/libomp.dylib' (no such file)"]

No display found. Using non-interactive Agg backend
Switched to: Agg
Traceback (most recent call last):
  File "/Users/anniezhou/Desktop/NeuralLCB_C/realworld_main.py", line 68, in <module>
    from xgboost import XGBRegressor
  File "/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/__init__.py", line 6, in <module>
    from . import tracker  # noqa
  File "/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/tracker.py", line 9, in <module>
    from .core import _LIB, _check_call, make_jcargs
  File "/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/core.py", line 269, in <module>
    _LIB = _load_lib()
  File "/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/core.py", line 222, in _load_lib
    raise XGBoostError(
xgboost.core.XGBoostError: 
XGBoost Library (libxgboost.dylib) could not be loaded.
Likely causes:
  * OpenMP runtime is not installed
    - vcomp140.dll or libgomp-1.dll for Windows
    - libomp.dylib for Mac OSX
    - libgomp.so for Linux and other UNIX-like OSes
    Mac OSX users: Run `brew install libomp` to install OpenMP runtime.

  * You are running 32-bit Python on a 64-bit OS

Error message(s): ["dlopen(/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/lib/libxgboost.dylib, 0x0006): Library not loaded: @rpath/libomp.dylib\n  Referenced from: <B22D7F05-77FA-34A6-8757-C605D2CFE1AD> /opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/lib/libxgboost.dylib\n  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/lib-dynload/../../libomp.dylib' (no such file), '/opt/anaconda3/envs/jaxcpu_tf28/bin/../lib/libomp.dylib' (no such file)"]

No display found. Using non-interactive Agg backend
Switched to: Agg
Traceback (most recent call last):
  File "/Users/anniezhou/Desktop/NeuralLCB_C/realworld_main.py", line 68, in <module>
    from xgboost import XGBRegressor
  File "/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/__init__.py", line 6, in <module>
    from . import tracker  # noqa
  File "/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/tracker.py", line 9, in <module>
    from .core import _LIB, _check_call, make_jcargs
  File "/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/core.py", line 269, in <module>
    _LIB = _load_lib()
  File "/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/core.py", line 222, in _load_lib
    raise XGBoostError(
xgboost.core.XGBoostError: 
XGBoost Library (libxgboost.dylib) could not be loaded.
Likely causes:
  * OpenMP runtime is not installed
    - vcomp140.dll or libgomp-1.dll for Windows
    - libomp.dylib for Mac OSX
    - libgomp.so for Linux and other UNIX-like OSes
    Mac OSX users: Run `brew install libomp` to install OpenMP runtime.

  * You are running 32-bit Python on a 64-bit OS

Error message(s): ["dlopen(/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/lib/libxgboost.dylib, 0x0006): Library not loaded: @rpath/libomp.dylib\n  Referenced from: <B22D7F05-77FA-34A6-8757-C605D2CFE1AD> /opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/lib/libxgboost.dylib\n  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/lib-dynload/../../libomp.dylib' (no such file), '/opt/anaconda3/envs/jaxcpu_tf28/bin/../lib/libomp.dylib' (no such file)"]

No display found. Using non-interactive Agg backend
Switched to: Agg
Traceback (most recent call last):
  File "/Users/anniezhou/Desktop/NeuralLCB_C/realworld_main.py", line 68, in <module>
    from xgboost import XGBRegressor
  File "/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/__init__.py", line 6, in <module>
    from . import tracker  # noqa
  File "/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/tracker.py", line 9, in <module>
    from .core import _LIB, _check_call, make_jcargs
  File "/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/core.py", line 269, in <module>
    _LIB = _load_lib()
  File "/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/core.py", line 222, in _load_lib
    raise XGBoostError(
xgboost.core.XGBoostError: 
XGBoost Library (libxgboost.dylib) could not be loaded.
Likely causes:
  * OpenMP runtime is not installed
    - vcomp140.dll or libgomp-1.dll for Windows
    - libomp.dylib for Mac OSX
    - libgomp.so for Linux and other UNIX-like OSes
    Mac OSX users: Run `brew install libomp` to install OpenMP runtime.

  * You are running 32-bit Python on a 64-bit OS

Error message(s): ["dlopen(/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/lib/libxgboost.dylib, 0x0006): Library not loaded: @rpath/libomp.dylib\n  Referenced from: <B22D7F05-77FA-34A6-8757-C605D2CFE1AD> /opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/lib/libxgboost.dylib\n  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/lib-dynload/../../libomp.dylib' (no such file), '/opt/anaconda3/envs/jaxcpu_tf28/bin/../lib/libomp.dylib' (no such file)"]

No display found. Using non-interactive Agg backend
Switched to: Agg
Traceback (most recent call last):
  File "/Users/anniezhou/Desktop/NeuralLCB_C/realworld_main.py", line 68, in <module>
    from xgboost import XGBRegressor
  File "/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/__init__.py", line 6, in <module>
    from . import tracker  # noqa
  File "/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/tracker.py", line 9, in <module>
    from .core import _LIB, _check_call, make_jcargs
  File "/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/core.py", line 269, in <module>
    _LIB = _load_lib()
  File "/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/core.py", line 222, in _load_lib
    raise XGBoostError(
xgboost.core.XGBoostError: 
XGBoost Library (libxgboost.dylib) could not be loaded.
Likely causes:
  * OpenMP runtime is not installed
    - vcomp140.dll or libgomp-1.dll for Windows
    - libomp.dylib for Mac OSX
    - libgomp.so for Linux and other UNIX-like OSes
    Mac OSX users: Run `brew install libomp` to install OpenMP runtime.

  * You are running 32-bit Python on a 64-bit OS

Error message(s): ["dlopen(/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/lib/libxgboost.dylib, 0x0006): Library not loaded: @rpath/libomp.dylib\n  Referenced from: <B22D7F05-77FA-34A6-8757-C605D2CFE1AD> /opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/site-packages/xgboost/lib/libxgboost.dylib\n  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/opt/anaconda3/envs/jaxcpu_tf28/lib/python3.9/lib-dynload/../../libomp.dylib' (no such file), '/opt/anaconda3/envs/jaxcpu_tf28/bin/../lib/libomp.dylib' (no such file)"]

